[VAS-857][VAS-869][VAS-870] feat: add repo skeleton and infra
pagopa/pagopa-gpd-payments-pull pull request #1
Opened 2024-03-21 16:08 UTC by alessio-cialini

#### List of Changes

 - Introduced missing maven wrapper
 - Updated actions with project name
 - Updated README.md
 - Introduced infra templates
 - Introduced missing helm

#### Motivation and Context

https://pagopa.atlassian.net/jira/software/c/projects/VAS/boards/540?selectedIssue=VAS-676

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-03-21 16:41 UTC, alessio-cialini commented
update_code

2024-03-21 16:43 UTC, alessio-cialini commented
_update_code_

2024-03-21 16:48 UTC, svariant approved these changes
🧑‍💻👍🏻

2024-03-25 09:46 UTC, jacopocarlini commented on .pre-commit-config.yaml
> +      - id: google-style-java
```suggestion
```

2024-03-25 09:49 UTC, jacopocarlini commented on helm/values-dev.yaml
> +  fullnameOverride: ""
```suggestion
  fullnameOverride: "gpd-payments-pull"
```

2024-03-25 09:50 UTC, jacopocarlini commented on helm/values-prod.yaml
> +  fullnameOverride: ""
```suggestion
fullnameOverride: "gpd-payments-pull"
```

2024-03-25 09:51 UTC, jacopocarlini commented on helm/values-uat.yaml
> +  fullnameOverride: ""
```suggestion
  fullnameOverride: "gpd-payments-pull"
```

2024-03-25 09:52 UTC, jacopocarlini commented on openapi/generate_openapi.sh
this is an old version. Use the new (you can see backoffice)

2024-03-25 09:54 UTC, jacopocarlini commented on infra/04_apim_api.tf
> +    // Backoffice External
```suggestion
```

2024-03-25 09:55 UTC, jacopocarlini commented on infra/04_apim_api.tf
> +  product_ids           = [local.apim.bo_external_product_psp_id]
check the product

2024-03-25 09:56 UTC, jacopocarlini commented on infra/99_locals.tf
> +    bo_helpdesk_product_id = "selfcare-bo-helpdesk"
check the product

2024-03-25 09:59 UTC, jacopocarlini commented on src/main/java/it/gov/pagopa/gpd/payments/pull/models/Installment.java
> +    private String nav;
add the descriptions for the opeanpi file

2024-03-25 10:00 UTC, jacopocarlini commented on src/main/java/it/gov/pagopa/gpd/payments/pull/models/PaymentNotice.java
> +    private String iupd;
ditto

2024-03-25 10:04 UTC, jacopocarlini requested changes
👍 
see the comments

2024-03-25 14:03 UTC, jacopocarlini reviewed
this is a great job! kudos 🚀 🥇

2024-03-25 14:08 UTC, jacopocarlini approved these changes

2024-03-25 14:12 UTC, merged